const scoringDimensionsSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "roiPotential",
    "dataReadiness",
    "implementationEase",
    "adoptionEase",
    "strategicLeverage",
    "riskContainment",
    "stakeholderUrgency",
  ],
  properties: {
    roiPotential: { type: "number", minimum: 1, maximum: 5 },
    dataReadiness: { type: "number", minimum: 1, maximum: 5 },
    implementationEase: { type: "number", minimum: 1, maximum: 5 },
    adoptionEase: { type: "number", minimum: 1, maximum: 5 },
    strategicLeverage: { type: "number", minimum: 1, maximum: 5 },
    riskContainment: { type: "number", minimum: 1, maximum: 5 },
    stakeholderUrgency: { type: "number", minimum: 1, maximum: 5 },
  },
};

const discoverySchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "companyName",
    "domain",
    "workflowName",
    "workflowOwner",
    "baselineMetric",
    "humanReviewPoint",
    "executiveGoal",
    "stakeholderNotes",
    "operatorNotes",
    "currentWorkflowSteps",
    "systemsInvolved",
    "estimatedVolume",
    "estimatedTimeSpent",
    "roughBusinessImpact",
    "constraints",
    "adoptionConcerns",
    "teamReadiness",
    "dataAvailability",
    "knownFailureModes",
  ],
  properties: {
    companyName: { type: "string" },
    domain: { type: "string" },
    workflowName: { type: "string" },
    workflowOwner: { type: "string" },
    baselineMetric: { type: "string" },
    humanReviewPoint: { type: "string" },
    executiveGoal: { type: "string" },
    stakeholderNotes: { type: "string" },
    operatorNotes: { type: "string" },
    currentWorkflowSteps: {
      type: "array",
      minItems: 3,
      maxItems: 8,
      items: { type: "string" },
    },
    systemsInvolved: {
      type: "array",
      minItems: 2,
      maxItems: 8,
      items: { type: "string" },
    },
    estimatedVolume: { type: "string" },
    estimatedTimeSpent: { type: "string" },
    roughBusinessImpact: { type: "string" },
    constraints: { type: "string" },
    adoptionConcerns: { type: "string" },
    teamReadiness: { type: "string", enum: ["low", "medium", "high"] },
    dataAvailability: { type: "string", enum: ["low", "medium", "high"] },
    knownFailureModes: {
      type: "array",
      minItems: 2,
      maxItems: 8,
      items: { type: "string" },
    },
  },
};

const evidenceItemSchema = {
  type: "object",
  additionalProperties: false,
  required: ["id", "text", "quote", "confidence"],
  properties: {
    id: { type: "string" },
    text: { type: "string" },
    quote: { type: "string" },
    confidence: { type: "string", enum: ["low", "medium", "high"] },
  },
};

const evidenceBackedClaimSchema = {
  type: "object",
  additionalProperties: false,
  required: ["id", "text", "evidenceIds", "assumptionToValidate"],
  properties: {
    id: { type: "string" },
    text: { type: "string" },
    evidenceIds: {
      type: "array",
      maxItems: 3,
      items: { type: "string" },
    },
    assumptionToValidate: { type: "string" },
  },
};

export const synthesisJsonSchema = {
  name: "tenex_discovery_synthesis",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "label",
      "summary",
      "discovery",
      "workflowBottlenecks",
      "discoveryEvidence",
      "assumptionsToValidate",
      "opportunities",
      "stakeholders",
      "adoptionRisks",
      "valueMetrics",
      "warnings",
    ],
    properties: {
      label: { type: "string" },
      summary: { type: "string" },
      discovery: discoverySchema,
      workflowBottlenecks: {
        type: "array",
        minItems: 3,
        maxItems: 5,
        items: evidenceBackedClaimSchema,
      },
      discoveryEvidence: {
        type: "array",
        minItems: 2,
        maxItems: 6,
        items: evidenceItemSchema,
      },
      assumptionsToValidate: {
        type: "array",
        minItems: 3,
        maxItems: 6,
        items: evidenceBackedClaimSchema,
      },
      opportunities: {
        type: "array",
        minItems: 3,
        maxItems: 4,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "id",
            "title",
            "description",
            "targetWorkflow",
            "pilotKind",
            "evidenceIds",
            "assumptionToValidate",
            "dimensions",
            "rationale",
            "notYet",
          ],
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            description: { type: "string" },
            targetWorkflow: { type: "string" },
            pilotKind: {
              type: "string",
              enum: ["workflow", "measurement", "reporting", "knowledge", "follow-up"],
            },
            evidenceIds: {
              type: "array",
              maxItems: 3,
              items: { type: "string" },
            },
            assumptionToValidate: { type: "string" },
            dimensions: scoringDimensionsSchema,
            rationale: { type: "string" },
            notYet: { type: "string" },
          },
        },
      },
      stakeholders: {
        type: "array",
        minItems: 3,
        maxItems: 5,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["role", "priority", "concern", "alignmentMove"],
          properties: {
            role: { type: "string" },
            priority: {
              type: "string",
              enum: ["primary", "supporting", "informed"],
            },
            concern: { type: "string" },
            alignmentMove: { type: "string" },
          },
        },
      },
      adoptionRisks: {
        type: "array",
        minItems: 3,
        maxItems: 5,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "risk",
            "signal",
            "mitigation",
            "owner",
            "evidenceIds",
            "assumptionToValidate",
          ],
          properties: {
            risk: { type: "string" },
            signal: { type: "string" },
            mitigation: { type: "string" },
            owner: { type: "string" },
            evidenceIds: {
              type: "array",
              maxItems: 3,
              items: { type: "string" },
            },
            assumptionToValidate: { type: "string" },
          },
        },
      },
      valueMetrics: {
        type: "array",
        minItems: 4,
        maxItems: 6,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["name", "baseline", "target", "owner", "cadence", "confidence"],
          properties: {
            name: { type: "string" },
            baseline: { type: "string" },
            target: { type: "string" },
            owner: { type: "string" },
            cadence: { type: "string" },
            confidence: { type: "string", enum: ["low", "medium", "high"] },
          },
        },
      },
      warnings: {
        type: "array",
        maxItems: 5,
        items: { type: "string" },
      },
    },
  },
} as const;
